package com.example.photoalbum;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

//declaring class as entity and assigning table name to it.
@Entity(tableName = "my_images")
public class MyImages {
    //setting id column as a primary key and it will automatically generated by the database.
    @PrimaryKey(autoGenerate = true)
    public  int imageId;
    //other columns of the table.
    public String imageTitle;
    public String imageDescription;
    //image stores in blob format in sqlite database so we are creating it with the type as array of bytes.
    public  byte[] image;
    //creating constructor of the class with all columns as a parameter except id column.
    public MyImages(String imageTitle, String imageDescription, byte[] image) {
        this.imageTitle = imageTitle;
        this.imageDescription = imageDescription;
        this.image = image;
    }
    //creating getters for all the columns of the table.
    public int getImageId() {
        return imageId;
    }

    public String getImageTitle() {
        return imageTitle;
    }

    public String getImageDescription() {
        return imageDescription;
    }

    public byte[] getImage() {
        return image;
    }
    //creating setter for id column as we require it while updating our data in the database.
    public void setImageId(int imageId) {
        this.imageId = imageId;
    }
}
